endroid_qr_code:
    writer: 'svg'
    size: 300
    margin: 5
    foreground_color: { r: 32, g: 32, b: 32 }
    background_color: { r: 255, g: 255, b: 255 }
    error_correction_level: medium # low, medium, quartile or high
    encoding: UTF-8
    label: Scan the code
    label_font_size: 0
    label_alignment: center # left, center or right
    label_margin: { b: 20 }
    #    logo_path: '%kernel.root_dir%/../public/favicon/favicon.ico'
    logo_width: 64
    logo_height: 64
    validate_result: false # checks if the result is readable
    writer_options:
        exclude_xml_declaration: true
