app_login:
    path: /login
    controller: App\Controller\SecurityController::login

pass_recovery:
    path: /passwordRecovery
    controller: App\Controller\SecurityController::recovery

reset_password:
    path: /resetPassword
    controller: App\Controller\SecurityController::reset_password

check_email:
    path: /checkEmail
    controller: App\Controller\SecurityController::check_email

app_logout:
    path: /logout

registration:
    path: /registration
    controller: App\Controller\RegistrationController::register

referral:
    path: /fand{id}
    controller: App\Controller\ReferralController::devourer
    requirements:
        refferal: '\d+'

code_confirm:    
    path: /user/confirm    
    controller: App\Controller\RegistrationController::confirmCode

send_code_confirm:
    path: /user/sendConfirm
    controller: App\Controller\RegistrationController::sendConfirmCode

register_fund_method:
    path: /user/registerFundMethod
    controller: App\Controller\RegistrationController::registerFundMethod

main:
    path: /
    controller: App\Controller\MainController::main

children_list:
    path: /children
    controller: App\Controller\ChildController::list

children_detail:
    path: /children/{id}
    controller: App\Controller\ChildController::detail
    requirements:
        id: '\d+'

news_list:
    path: /news
    controller: App\Controller\NewsController::list

news_cards:
    path: /news/cards
    controller: App\Controller\NewsController::cards

news_detail:
    path: /news/{id}
    controller: App\Controller\NewsController::detail
    requirements:
        id: '\d+'

partners:
    path: /partners
    controller: App\Controller\MainController::partners

docs:
    path: /docs
    controller: App\Controller\MainController::docs

reports:
    path: /reports
    controller: App\Controller\MainController::reports

contacts:
    path: /contacts
    controller: App\Controller\MainController::contacts

sms:
    path: /sms
    controller: App\Controller\MainController::sms

help:
    path: /needhelp
    controller: App\Controller\MainController::help

donate_help:
    path: /help
    controller: App\Controller\DonateController::main

donate_online_help:
    path: /dist/online-help.html
    controller: App\Controller\DonateController::main

donate:
    path: /donate
    controller: App\Controller\DonateController::main

donate_ok:
    path: /donate/ok
    controller: App\Controller\DonateController::ok

donate_no:
    path: /donate/no
    controller: App\Controller\DonateController::no

donate_fail:
    path: /donate/fail
    controller: App\Controller\DonateController::fail

donate_status:
    path: /donate/status
    controller: App\Controller\DonateController::status

send_reminder:
    path: /donate/sendReminder
    controller: App\Controller\DonateController::sendReminder

account_main:
    path: /account
    controller: App\Controller\AccountController::main

account_myaccount:
    path: /account/myaccount
    controller: App\Controller\AccountController::myAccount

account_history:
    path: /account/history
    controller: App\Controller\AccountController::history

account_referrals:
    path: /account/referrals
    controller: App\Controller\AccountController::referrals

account_download:
    path: /account/downloadImage
    controller: App\Controller\AccountController::downloadImage

account_recurrent:
    path: /account/recurrent
    controller: App\Controller\AccountController::recurrent

account_recurrent_remove:
    path: /account/recurrent/{id}
    methods: post
    controller: App\Controller\AccountController::recurrent_remove
    requirements:
        id: '.+'

account_payout_request:
    path: /account/sendPayoutRequest
    methods: POST
    controller: App\Controller\AccountController::sendPayoutRequest

panel_main:
    path: /panel
    controller: App\Controller\PanelController::main

panel_user:
    path: /panel/users
    controller: App\Controller\PanelController::users

panel_user_edit:
    path: /panel/users/{id}
    controller: App\Controller\UserController::edit
    requirements:
        id: '\d+'

panel_user_delete:
    path: /panel/users/{id}/delete
    controller: App\Controller\UserController:delete
    requirements:
        id: '\d+'

panel_documents:
    path: /panel/documents
    controller: App\Controller\DocumentController::index

panel_documents_add:
    path: /panel/documents/add
    controller: App\Controller\DocumentController::add

panel_documents_edit:
    path: /panel/documents/{id}
    controller: App\Controller\DocumentController::edit
    requirements:
        id: '\d+'

panel_documents_delete:
    path: /panel/documents/{id}/delete
    controller: App\Controller\DocumentController:delete
    requirements:
        id: '\d+'

panel_requests:
    path: /panel/requests
    controller: App\Controller\PanelController::requests

user_controller:
    path: /user
    controller: App\Controller\UserController::index

panel_child:
    path: /panel/child
    controller: App\Controller\ChildController::list_panel

panel_child_add:
    path: /panel/child/add
    controller: App\Controller\ChildController::add

panel_child_edit:
    path: /panel/child/{id}
    controller: App\Controller\ChildController::edit
    requirements:
        id: '\d+'

panel_child_del:
    path: /panel/child/del/{id}
    controller: App\Controller\ChildController::delete
    requirements:
        id: '\d+'

panel_recurring:
    path: /panel/recurring
    controller: App\Controller\RecurringController::list

# ???!
panel_child_delete:
    path: /panel/recurring/{id}
    controller: App\Controller\RecurringController::delete
    requirements:
        id: '\d+'

panel_config:
    path: /panel/config
    controller: App\Controller\ConfigController::edit

paysms:
    path: /paysms
    controller: \App\Controller\DonateController::sms
